# This workflow initializes a Python environment and executes
# the specified .py file/s at a scheduled time of 11:30pm
# each day. In this case the views.py file located in the
# main branch of this repository.

name: GitHub Metrics

on:
#  push:
#    branches:
#      - main  
      
  schedule:
    - cron: '30 23 * * *'  # Runs at 11:30pm UTC every day

jobs:
  extract-views:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt  # Contains any dependencies that are not part of the Python standard library
      - name: Run Python script to extract views
        env: 
          TOKEN: ${{ secrets.DATA_TOKEN }}        
        run: python views.py # Extract GitHub views and append to CSV  
